3.0.12.7

diff --git a/ModLauncher_Data/StreamingAssets/Tools/Windows/PortableGit/usr/bin/getemojis b/ModLauncher_Data/StreamingAssets/Tools/Windows/PortableGit/usr/bin/getemojis
--- a/ModLauncher_Data/StreamingAssets/Tools/Windows/PortableGit/usr/bin/getemojis
+++ b/ModLauncher_Data/StreamingAssets/Tools/Windows/PortableGit/usr/bin/getemojis
@@ -5,6 +5,9 @@ trace () {
 	true
 }
 
+wgetfirst=false
+#wgetfirst=true
+
 case "$1" in
 -sh)	postproc=cat
 	shift;;
@@ -19,14 +22,29 @@ mintty)
 	exit;;
 esac
 
-emojisurl0=http://www.unicode.org/emoji/charts/full-emoji-list.html
-emojisurl1=http://www.unicode.org/emoji/charts/full-emoji-modifiers.html
+emojisurl0=https://www.unicode.org/emoji/charts/full-emoji-list.html
+emojisurl1=https://www.unicode.org/emoji/charts/full-emoji-modifiers.html
 
 download () {
-	if type curl
-	then	curl -RO -z `basename $1` $1
-	else	wget -N -t 1 $1
-	fi
+	if $wgetfirst
+	then	wget -N -t 1 "$1"
+	elif type curl
+	then	# prefer curl because it works better behind proxies
+		if [ -f `basename "$1"` ]
+		then	curl -RO -z `basename "$1"` "$1"
+		else	# avoid "Warning: Illegal date format for -z"
+			curl -RO "$1"
+		fi
+	else	wget -N -t 1 "$1"
+	fi ||
+	(echo "[41;30mFILE: $1[m" >&2
+	 echo "[41;30mERROR: download failed, file incomplete[m" >&2
+	 if [ -f `basename "$1"` ]
+	 then	# enforce fresh download next time
+		touch -d 1970-01-01 `basename "$1"`
+	 fi
+	 return 9
+	)
 }
 
 case "$1" in
@@ -142,7 +160,7 @@ do	sel="$sel$seli"
 	mkdir -p "$1"
 	shift
 done
-mkdir -p common
+mkdir -p common google
 
 export sel
 
@@ -179,6 +197,11 @@ img0 () {
   echo "$1" | base64 -d > common/$ename.png
 }
 
+imgg () {
+  echo " google $ename.png" >&2
+  echo "$1" | base64 -d > google/$ename.png
+}
+
 img () {
   style=$(( $style + 1 ))
   case $sel in
@@ -198,6 +221,7 @@ imgskip () {
 cat "$emojis0" "$emojis1" |
 sed -e "s/^.*name='\([^']*\)'.*U+.*/name \1/" -e "t name" \
     -e "s/.*—.*/imgskip/" -e t \
+    -e "s@^.*….*src='data:image/png;base64,\([^']*\)'.*src='data:image/png;base64,\([^']*\)'.*@imgg \1\nimg0 \2@" -e t \
     -e "s@^.*….*src='data:image/png;base64,\([^']*\)'.*@img0 \1@" -e t \
     -e "s@^.*src='data:image/png;base64,\([^']*\)'.*@img \1@" -e t \
     -e d \
